CREATE TABLE IF NOT EXISTS `project_jd2`.`T_PROFILE` (
  `USER_ID` INT(5) NOT NULL,
  `ADDRESS` VARCHAR(90) NOT NULL,
  `TELEPHONE` VARCHAR(15) NOT NULL);
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_ORDER` (
  `ID_ORDER` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(5) NOT NULL,
  `ITEM_ID` INT(11) NOT NULL,
  `CREATED` DATETIME NOT NULL,
  `QUANTITY` INT(11) NOT NULL,
  PRIMARY KEY (`ID_ORDER`));
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_NEWS` (
  `ID_NEWS` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(5) NOT NULL,
  `TITLE` VARCHAR(90) NOT NULL,
  `CONTENT` MEDIUMTEXT NOT NULL,
  `CREATION_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID_NEWS`));
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_ITEM` (
  `ID_ITEM` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(60) NOT NULL,
  `DESCRIPTION` MEDIUMTEXT NOT NULL,
  `UNIQUE_NUMBER` VARCHAR(30) NOT NULL,
  `PRICE` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`ID_ITEM`));
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_COMMENT` (
  `ID_COMMENT` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(5) NOT NULL,
  `CONTENT` MEDIUMTEXT NOT NULL,
  `CREATED` DATETIME NOT NULL,
  PRIMARY KEY (`ID_COMMENT`));
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_AUDIT` (
  `ID_AUDIT` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(5) NOT NULL,
  `EVENT_TYPE` VARCHAR(60) NOT NULL,
  `CREATED` DATETIME NOT NULL,
  PRIMARY KEY (`ID_AUDIT`));
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_USER` (
  `USER_ID` INT(5) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` INT(11) NOT NULL,
  `EMAIL` VARCHAR(35) NOT NULL,
  `PASSWORD` VARCHAR(30) NOT NULL,
  `FIRST_NAME` VARCHAR(30) NOT NULL,
  `LAST_NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`));
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_ROLE_PERMISSION` (
  `PERMISSION_ID` INT(11) NOT NULL,
  `ROLE_ID` INT(11) NOT NULL);
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_ROLE` (
  `ID_ROLE` INT(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_ROLE`));
  
  CREATE TABLE IF NOT EXISTS `project_jd2`.`T_PERMISSION` (
  `ID_PERMISSION` INT(11) NOT NULL AUTO_INCREMENT,
  `PERMISSION_NAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_PERMISSION`));